### ISSUE TITLE
Can't run hostNetwork pod on CRI-O with crictl runp

### ISSUE THREAD

**Issue by Nefelim4ag** [kubernetes-sigs/cri-tools#547]
CRI-O try use CNI for configure pod network, even if i declare use hostNetwork in pod description
But kubelet successful create pods with hostNetworks, so i think that a crictl bug

**Comment by saschagrunert** [comment]
Hey @Nefelim4ag, can you please provide us a reproducer for this bug and the expected output?

**Comment by Nefelim4ag** [comment]
Oh, i will try setup clear environment and get reproducer, np

**Comment by Nefelim4ag** [comment]
Easy:
1. Setup bare Ubuntu 18.04
2. apt install cri-o-1.15
3. Download latest crictl
4. rm -v /etc/cni/net.d/*
5. Deploy pod with hostNetwork: true

```
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: kube-system
spec:
  hostNetwork: true
  priorityClassName: system-node-critical
  restartPolicy: Always
  terminationGracePeriodSeconds: 0
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 50m
          memory: 16Mi
        requests:
          cpu: 5m
          memory: 8Mi
```

**Comment by saschagrunert** [comment]
Hm, to me this does not look like an issue with crictl itself, but more a configuration thing. Does `With CNI` mean that you have a plain installation of the Ubuntu CRI-O package (from the project atomic PPA?).

**Comment by Nefelim4ag** [comment]
Yep, plain installation from PPA of project atomic

But cri-o must not call CNI for hostNetwork pod, even with CNI or without,
you think that a cri-o issue?

**Comment by saschagrunert** [comment]
Oh, no. I think you're mixing up the Container Runtime Interface (CRI) API and the Kubernetes manifest specification. crictl interfaces with the CRI API, so running this should work without having a valid CNI config:

```yaml
---
metadata:
  name: sandbox
  namespace: crio
linux:
  security_context:
    namespace_options:
      network: 2
```

`network: 2` indicates the node network type. :)
