### ISSUE TITLE
crictl logs -f, the follow option does not work, instead it repeats the same output again and again

### ISSUE THREAD

**Issue by gigilee** [kubernetes-sigs/cri-tools#866]
#### What happened:
Our kubernetes cluster is recently upgraded to 1.20.8.  We use OKE. The container engine is switched from docker to crio.
We found that our crictl logs with follow options do not work at all.  It simply repeats the same outout continouesly.
I deployed a simple busybox with the following yaml file:
```
apiVersion: apps/v1                                                                              
kind: Deployment                                                                                 
metadata:                                                                                        
  name: busybox-deployment                                                                       
  labels:                                                                                        
    app: busybox                                                                                 
spec:                                                                                            
  replicas: 2                                                                                    
  selector:                                                                                      
    matchLabels:                                                                                 
      app: busybox                                                                               
  template:                                                                                      
    metadata:                                                                                    
      labels:                                                                                    
        app: busybox                                                                             
    spec:                                                                                                                             
        - name: "tmp-vol"                                                                        
          emptyDir: {}                                                                           
                                                                                                 
      containers:                                                                                
      - name: busybox                                                                            
        image: iad.ocir.io/paasdevoic/giglee/busybox:latest                                      
        imagePullPolicy: IfNotPresent                                                            
        command: ['sh', '-c', 'echo Container 1 is Running ; date; sleep 3600']                  
        volumeMounts:                                                                                                                        
          - name: "tmp-vol"                                                                      
            mountPath: "/tmp"                                                                    
```
This is what I see from the output:
```
Container 1 is Running
Wed Dec 22 01:44:53 UTC 2021
Container 1 is Running
Wed Dec 22 01:44:53 UTC 2021
Container 1 is Running
Wed Dec 22 01:44:53 UTC 2021
Container 1 is Running
Wed Dec 22 01:44:53 UTC 2021
```
#### What you expected to happen:
crictl with follow option to output latest logs in a stream fashion instead of start from the very beginning every minute or so.
There should be only 2 lines in the output
```
Container 1 is Running
Wed Dec 22 01:44:53 UTC 2021
```
#### How to reproduce it (as minimally and precisely as possible):
crictl logs -f <containerid>

#### Environment:

- Container runtime or hardware configuration:
 **Currently where the problem happens:**
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.20.2
RuntimeApiVersion:  v1alpha1

**Previously when we don't have the problem:**
 Version:  0.1.0
  RuntimeName:  docker
  RuntimeVersion:  19.03.11-ol
  RuntimeApiVersion:  1.40.0

- OS (e.g: `cat /etc/os-release`):
Oracle Linux
VERSION="7.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Oracle Linux Server 7.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.9

- Kernel (e.g. `uname -a`):

Linux oke-czgcnrzgqzd-n3dimzwgbsg-sddfwxbw2xq-5-151116 5.4.17-2136.300.7.el7uek.x86_64 #253  x86_64 x86_64 x86_64 GNU/Linux

- Others:
